# Generated by Django 5.2.18 on 2026-10-06 21:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='founded_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-4000), django.core.validators.MaxValueValidator(2026)]),
        ),
    ]
